index.js
package.json

i renamed protocol version to database version and used an int to represent it instead as it doesn't make sense to have minor & patch on something like this.
lmk what else we can do here before we merge into master
this will be required for [cabal-cli's multi cabal pr](https://github.com/cabal-club/cabal/pull/89)

Database version Rename

---

views/topics.js

Made the call to callback unconditional, so that you don't have to
wait forever until your callback gets invoked if anything goes wrong. ;)

Fixed error propagation bug

---

views/messages.js
views/topics.js

Changed the order of the `xtend()` assignment, so that passed opts
takes priority making it possible to override the
`{reverse: true}`  with a `false` value instead.
Also added some semi-accurate documentation to that method based on
assumptions.

Allow messages.read() opts to take priority over defaults

---

index.js

I incorrectly set the maxFeeds option on the kappa-core constructor. To actually get through to hypercore-protocol it should be set on the replicate function.
Fixes https://github.com/cabal-club/cabal/issues/106
Thanks to @karissa for pointing me in the right direction!

Send maxFeeds option on kappa-core replicate to actually get through to hypercore-protocol

---

README.md
index.js
package.json
swarm.js
test/test.js

Previously 'swarm.js' would send a 32-byte payload before handing off to cabal-core#replicate. This
a) isn't necessary, since discovery-swarm can send an arbitrary payload anyway, and
b) makes other clients (like Message Land's gateway) unable to use straight-up cabal-core#replicate to sync with e.g. CLI peers
This also adds some tests for same-process and network sync, and makes the 'swarm' API be a member of the cabal instance instead of something to require separately.

PROTOCOL BREAKING: use discovery-swarm for sending peer key

---

README.md
index.js
package.json
test/test.js

This patch makes it possible to use durable storage from a levelup or leveldown instance as `opts.db` instead of always using memdb.

opts.db to pass durable storage

---

index.js

i was working on cabal client when i noticed the following
1. cabal-core doesn't set its max listeners limit
1. levelup sets it to infinity
so i figured we would do the same [thing](https://github.com/Level/levelup/blob/master/lib/levelup.js#L34-L35) in the hopes of it solving https://github.com/cabal-club/cabal-cli/issues/110
tagging a few reviewers to make sure this isn't really dumb

set max listeners for event emitter

---

views/messages.js

What was happening was that when a timestamp, which are
monotonic-timestamps, included an e.g. ".001" suffix, it would be
considered as "in the future" if the indexer was quick enough to pick it
up, and then be converted to "new Date().getTime()". So if two messages
were written to a channel fast enough, BOTH would get set to "new
Date().getTime()" and the second would overwrite the first in leveldb.
This change ensures that proper monotonic-timestamps are used
throughout.

encode now-timestamps properly to avoid overwrites

---

.travis.yml
README.md
index.js
package.json
swarm.js
test/mod.js
test/test.js
views/moderation.js

This is a breaking protocol change.
The new version of hypercore seems to improve some issues with sync getting stuck. Hoping it will improve sync quality & performance for us.

upgrade to hypercore-protocol@7 via kappa-core

---

swarm.js

Trying to see if I can increase cabal's reliability by hosting an additional
dns-discovery server.
If you'd like to host one too, run these commands on your VPS / machine with a public IP:
```
npm i -g dns-discovery
dns-discovery listen --port=9090 --ttl=30
```
and send a PR or reply here.

add dns-discovery server: eight45.net

---

index.js
test/mod.js
views/moderation.js

this PR adds basic support for Cabal URIs containing mod & admin keys, e.g. 
`cabal://[0-9A-Fa-f]{64}?mod=<key>` and is related to https://github.com/cabal-club/cabal-client/pull/41

add support for mod & admin keys in cabal key uri

---

index.js

apparently the `new URL()` behaviour is unpredictable. chrome, node, and
firefox all return different values when a cabal key is passed in. 
(`searchParams` always seems to work, however)
for node the cabal key can be found in `uri.host`, in chromium/electron
it's found at `uri.hostname`, for firefox both of those are empty, but
`uri.pathname` gives the cabal key prepended with two slashes (but that
doesn't work in node...)
until [the IANA change](https://github.com/datprotocol/DEPs/issues/66#issuecomment-629016786) lands / has a standardizing effect, let's just use
a regex to capture it.
this patch also changes `isHypercoreKey` to use the same regex as `cabal-client`. 
i dunno if hypercore has a strict lower-case character requirement, however
fixes #88

use regex to capture cabal key instead of URL

---

README.md
index.js
views/moderation.js

This secondary index and moderation API is required to make `/inspect` from the [roadmap](https://github.com/cabal-club/commons/issues/10) work.
The patch adds a listModerationBy(key) method which streams primary documents associated with moderation actions for a given user.

listModerationBy

---

index.js
test/mod.js
views/moderation.js

- core no longer does URI parsing (cabal-client can do that instead)
- accepts `opts.modKeys`, `opts.adminKeys`
- some lifecycle fixes around the mod view

Some more moderation changes

---

test/mod.js
views/moderation.js

This is a WIP PR because I am unfamiliar with the testing suite, so it only fixes my problem presently.
The issue is that if you treat `cabal.moderation.list` as a read stream instead of utilizing its callback, you get this:
```
Uncaught TypeError: The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type object
at chunkInvalid (node_modules/readable-stream/lib/_stream_readable.js:313:10)
at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:258:31)
at Duplexify.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:241:10)
at Duplexify._forward (node_modules/duplexify/index.js:172:26)
at Readable.onreadable (node_modules/duplexify/index.js:136:10)
at emitReadable_ (node_modules/read-only-stream/node_modules/readable-stream/lib/_ …
```

duplexify must be in object mode for mod streams

---

README.md

Flags are an oft-referred to concept but they aren't enumerated in the documentation. Per a coversation in the default cabal:
```
<kira> right now each user can have flags from set of ["hidden", "admin", "mod"]
<kira> per user perspective
```

Document possible flags for `listByFlag`

---

README.md
index.js
swarm.js

add a preferredPort to listen for hyperswarm connections on. the
preferredPort is smart enough that if it is blocked, hyperswarm will try
preferredPort+1, preferredPort+2 before giving up. see the hyperswarm code:
https://github.com/hyperswarm/network/blob/ad41b0c2ac19dbf92865e481282ba6ac6e513d57/index.js#L150-L162
this allows people with highly configured firewalls to port forward a
single port for cabal, which they can themselves configure in their
clients.
fix #98

add preferredPort (default 13331) to core opts

---

index.js
views/channel-archiving.js

This PR implements support for archiving of channels, see more background info in https://github.com/cabal-club/cabal-client/issues/68 and https://github.com/cabal-club/cabal-client/issues/16.
Archiving a channel is intended to hide the channel from channel browsers, and support for this will be added in cabal-client once this is finished & after this is merged. Only moderators or admins are allowed to archive channels—the local user is always allowed to archive channels, as they are always regarded as an admin in our subjective moderation system.

Implement channel archiving

---

package.json
swarm.js

HAYOO
This PR sets the `browser` field of `package.json` so that we can do some cool hyperswarm-webbing. It also updates a couple of the core dependencies, mimicking the updates needed to make [caballo](https://github.com/cblgh/caballo) work initially. 
With this patch in place, I can successfully browserify cabal-core & query it in the browser (albeit I have only done a couple superficial tests so far, like making sure `core.ready` fires & executing `core.getLocalKey(cb)`. but it is very very promising :3)

Update core deps & set browser field

---

index.js

I've been wanting to use this function in cabal-client for a while. In the cabal-client PR https://github.com/cabal-club/cabal-client/pull/76, which is enabling browserifiying the lib, this turned out to be essential (dat-dns would cause browser complaints if we tried to lookup dns records on `https://<cabal-key>`. Thus this PR!

export Cabal.isHypercoreKey

---

package.json

There was a tiny discrepancy where some parts were using `sodium-native@3.2.1` and others using `sodium-native@2.4.9`, which for some reason had to compile on linux.
Reduces install time from about 1 minute 40 seconds to sub 10 seconds.

Upgrade sodium-universal for faster install

---

README.md
index.js
test/private.js
views/private-messages.js

Hey @cblgh, this is per our earlier discussion! Here is my new proposal for the structure of private messages & encrypted messages in general:
1. Use a generic encryption format (no `private/chat`, just use `text/chat` so existing logic can be more easily reused).
2. Continue using `'type: "encrypted"` on ciphertext payloads. This means encrypted messages won't affect any existing views, since it's a type unknown to them. Views can opt-in to supporting encrypted messages as needed.
3. I decided against a `cipher_type` key on the ciphertext message, since we didn't have a clear decision on the pros/cons of that. However, we can add later /wo breaking backwards compatibility.
It's just the same as regular chat message, but encrypted, and the inner payload has a `recipients` key instead of …

Use generic encrypted payloads
